apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: laminate-rcdata-pipeline
  annotations:
    scenarios.ai.sap.com/description: "ingest quality defect root cause analysis data to workflows"
    scenarios.ai.sap.com/name: "Laminate Quality root cause analysis defect prediction"
    executables.ai.sap.com/description: "Train with Laminate printing root cause analysis data"
    executables.ai.sap.com/name: "training0"
    artifacts.ai.sap.com/laminatedefectdata.kind:  "dataset"
    artifacts.ai.sap.com/laminatedefectmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "Laminate_defect_Rootcause_datalines"
    ai.sap.com/version: '2.0'
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: mypipeline
  arguments:
    parameters: []
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    inputs:
      artifacts:
        - name: rootcauseanalysisdata
          path: /app/data/
    outputs:
      artifacts:
        - name: rootcausemodel
          globalName: rootcause_analysis_model
          path: /app/model/
          archive:
            none: 
              {}
    container:
      image: docker.io/pareshkolte/rootcause_analysis
      command: ["/bin/sh", "-c"]
      env: []
      args:
        - "python /app/src/main.py"
