apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "rc-data-pipeline"
  annotations:
    scenarios.ai.sap.com/description: "root cause analysis to predict the department"
    scenarios.ai.sap.com/name: "Root cause analysis department prediction"
    executables.ai.sap.com/description: "Root cause analysis for department prediction"
    executables.ai.sap.com/name: "training1"
    artifacts.ai.sap.com/rootcauseanalysisdata.kind:  "dataset"
    artifacts.ai.sap.com/rootcauseanalysismodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "rc-data-pipeline"
    ai.sap.com/version: '2.0'
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: mypipeline
  arguments:
    parameters: []
  templates:
    - name: mypipeline
      steps:
        - - name: mytrainer
            template: mycodeblock1

    - name: mycodeblock1
      inputs:
        artifacts:
          - name: rootcauseanalysisdata
            path: /app/data/rootcause_data.csv
      outputs:
        artifacts:
          - name: rootcauseanalysismodel
            globalName: rootcause_department_model
            path: /app/model/
            archive:
              none: {}
      container:
        image: docker.io/pareshkolte/rootcause_department_prediction:01
        command: ["/bin/sh", "-c"]
        args:
          - "mkdir -p /app/model && python /app/src/main.py"
