apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: laminate-data-pipeline
  annotations:
    scenarios.ai.sap.com/description: "ingest quality defect data to workflows"
    scenarios.ai.sap.com/name: "Laminate Quality defect prediction"
    executables.ai.sap.com/description: "Train with Laminate printing machine parameter data"
    executables.ai.sap.com/name: "training1"
    artifacts.ai.sap.com/laminatedefectdata.kind:  "dataset"
    artifacts.ai.sap.com/laminatedefectmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "Laminate_defect_datalines"
    ai.sap.com/version: '2.0'
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: mypipeline
  arguments:
    parameters: []
  templates:
    - name: mypipeline
      steps:
        - - name: mytrainer
            template: mycodeblock1

    - name: mycodeblock1
      inputs:
        artifacts:
          - name: laminatedefectdata
            path: /app/data/input.csv
      outputs:
        artifacts:
          - name: laminatedefectmodel
            globalName: laminate_quality_defect
            path: /app/model/
            archive:
              none: {}
      container:
        image: docker.io/pareshkolte/laminate_defect_train:01
        command: ["/bin/sh", "-c"]
        args:
          - "mkdir -p /app/model && python /app/train_model.py --input /app/data/input.csv --output /app/model"
